/**
 * Bakes the Hugeicons we use into src/renderer/icons.js.
 *
 * The renderer runs unbundled ES modules straight off disk, so it can't resolve
 * bare specifiers into node_modules. Instead we read the icon data from
 * @hugeicons/core-free-icons here and emit ready-made SVG markup.
 *
 *   npm run icons
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Local name → Hugeicons export. Keep sorted by local name.
const ICONS = {
  alert: 'Alert02Icon',
  chevron: 'ArrowRight01Icon',
  clock: 'Clock01Icon',
  close: 'Cancel01Icon',
  code: 'SourceCodeIcon',
  cog: 'Settings01Icon',
  copy: 'Copy01Icon',
  filter: 'FilterIcon',
  flash: 'FlashIcon',
  folder: 'Folder01Icon',
  inbox: 'InboxIcon',
  key: 'Key01Icon',
  layers: 'Layers01Icon',
  moon: 'Moon02Icon',
  more: 'MoreHorizontalIcon',
  plus: 'PlusSignIcon',
  save: 'FloppyDiskIcon',
  search: 'Search01Icon',
  send: 'SentIcon',
  sidebar: 'SidebarLeft01Icon',
  spinner: 'Loading03Icon',
  sun: 'Sun03Icon',
  terminal: 'CommandLineIcon',
  trash: 'Delete02Icon',
  wrap: 'TextWrapIcon'
};

const kebab = (name) => name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);

const toMarkup = (nodes) =>
  nodes
    .map(([tag, attrs]) => {
      const serialized = Object.entries(attrs)
        .filter(([name]) => name !== 'key')
        .map(([name, value]) => `${kebab(name)}="${value}"`)
        .join(' ');
      return `<${tag} ${serialized}/>`;
    })
    .join('');

const entries = [];
for (const [local, exported] of Object.entries(ICONS)) {
  const { default: nodes } = await import(`@hugeicons/core-free-icons/${exported}`);
  entries.push(`  ${local}: '${toMarkup(nodes).replace(/'/g, "\\'")}'`);
}

const out = `// Generated by scripts/build-icons.mjs — run \`npm run icons\` to refresh.
// Source: @hugeicons/core-free-icons (MIT), stroke style, 24x24 viewBox.
export const ICONS = {
${entries.join(',\n')}
};
`;

const target = path.join(fileURLToPath(new URL('../src/renderer/', import.meta.url)), 'icons.js');
await writeFile(target, out);
console.log(`icons.js: ${entries.length} icons`);
